### ISSUE TITLE
Gesetzliche Mindestpausenzeiten berücksichtigen

### ISSUE THREAD

**Issue by mrlugilugi** [moritzluedtke/sisosign#40]
Man könnte per default bzw. Auswahl in den Einstellungen die gesetzlich vorgeschriebenen Pausenzeiten ab 6 Stunden (30 Minuten) und ab 9 Stunden (45 Minuten) Arbeit berücksichtigen. Ansonsten ist der Wert für die erreichten 10 Stunden nicht korrekt, wenn man 30 Minuten einstellt. 🔢 
https://www.arbeitsrechte.de/pausenregelung/

Beste Grüße
Sören :)

**Comment by moritzluedtke** [comment]
Sehr guter Vorschlag! Vielen Dank dafür! Ich werd das auf jeden Fall in irgendeiner Art und Weise einbauen. Man müsste mal die unterschiedlichen Konstellationen aufzeichnen, da manche Firmen ja auch 50 Minuten Pause abziehen. 

Zudem wird ja ab 6h oft „hochgerampt“ bis man auf 45 Minuten Pause ist. Also mit jeder Minute mehr über 6h wächst auch die angezogene Pause um diese Zeit.

**Comment by moritzluedtke** [comment]
Ich werde den Gedanken nicht los, dass dies kein triviales Feature wird.

@mrlugilugi kannst du vielleicht zum Start einmal die Regelung bei euch auflisten, wann wie viel Pause abgezogen wird?

Ich versuche das anhand meiner Buchungen auch mal bei uns auseinanderzudrüseln (<- Fachwort ;) ).

**Comment by mrlugilugi** [comment]
Also ich denke, dass einfachste (und auch bei uns eingesetzte) Modell ist die Einhaltung der gesetzlichen Mindestzeiten.
Das heißt bei einer (Netto-)Arbeitszeit zwischen 6 und 9 Stunden werden automatisch 30 Minuten abgezogen. Ab 9 Stunden Arbeitszeit werden automatisch 45 Minuten abgezogen. Ohne Gewähr. Aber macht am meisten Sinn ^^

**Comment by moritzluedtke** [comment]
Alles klar. Dann baue ich das erstmal so als ersten Schritt ein und auch die Option, dies zu deaktivieren, falls jemand das möchte. Im nächsten Schritt baue ich dann die Regelung ein, wie es bei uns funktioniert.

**Comment by moritzluedtke** [comment]
Doch nochmal ne Frage.
Also bei 6h Nettoarbeitszeit stehen mir ja 30 Minuten Pause zu. Das heißt, wenn jemand 6h Nettoarbeitszeit hat, gibt es erstmal keinen Abzug. Dann aber von 6h an bis 6h 30m wird quasi die Mittagspause abgezogen, also kriegt er in der Zeit keine Nettoarbeitszeit dazu. Und das gleiche Spiel dann ab 9h?

Einmal beispielhaft in Tabellenform:

| Eingestempelt für (Bruttoarbeitszeit) | Am Ende angerechnete Nettoarbeitszeit |
|---------------------------------------|---------------------------------------|
| 6h                                    | 6h                                    |
| 6h 15m                                | 6h                                    |
| 6h 30m                                | 6h                                    |
| 6h 45m                                | 6h 15m                                |
| 9h                                    | 8h 30m                                |
| 9h 05m                                | 8h 30m                                |
| 9h 15m                                | 8h 30m                                |
| 9h 30m                                | 8h 45m                                |

**Comment by mrlugilugi** [comment]
Ja genau, ich denke dabei wird auf die Vernunft des Arbeitnehmers gesetzt und ein Auge zugedrückt. Wenn ein Arbeitnehmer 6h01m brutto arbeitet und aber 30 Minuten zwischendurch Pause macht, "bescheißt" er den Arbeitgeber eben um 29 Minuten Arbeitszeit. Paranoide Unternehmen ziehen eben pauschal 30 Minuten ab 6h00m01s ab, dann bist du netto bei 5h31m 😄 Da ich solche "Grenzfälle" bisher bei keinem Arbeitgeber ausprobiert habe, ist das natürlich alles ohne Gewähr 😃

**Comment by moritzluedtke** [comment]
Update: Das Feature ist jetzt in Arbeit. Habe am Wochenende etwa 3/4 davon implementiert.

**Comment by moritzluedtke** [comment]
Erledigt in `v2.3.0` ✅
