### ISSUE TITLE
Button zum sofortigem Einstempeln

### ISSUE THREAD

**Issue by g-wolter** [moritzluedtke/sisosign#66]
Zum schnelleren EInstempeln einen Button der die aktuelle Zeit in die Felder überträgt oder, sofern nicht von User gesetzt, die aktuelle Zeit beim öffnen der Website in das Einstempelfeld eintragen.

**Comment by moritzluedtke** [comment]
Gute Idee! Würde auch so etwas wie "Stempel mich vor 5 Minuten ein" Sinn ergeben?
Ich persönlich Stempel mich im Home Office immer ab PC Start ein. Bis zum Öffnen der Website vergehen dann aber 3-5 Minuten. 

Die Idee, per Einstellung sich automatisch bei Website Besuch einstellen zu lassen, finde ich auch sehr gut. In dem Fall würde ich den Button aber ausblenden.

Was meinst du?

**Comment by g-wolter** [comment]
Ja, das macht auf jeden Fall Sinn. Dieses issue kann natürlich auch gerne #60 weichen.

**Comment by moritzluedtke** [comment]
Wird vermutlich heute noch released.

**Comment by moritzluedtke** [comment]
Ist ab Version `2.4.0` mit dabei. Danke für das Feedback :)
